<a href="https://colab.research.google.com/github/lucianogasquess/Calculadora-de-partidas-Rankeadas/blob/main/DataScience_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
w1, w2, w3 = 0.3, 0.2, 0.5
print(w1)
print(w2)
print(w3)

0.3
0.2
0.5


In [ ]:
 # REGIAO A
regiaoA_temp = 22
regiaoA_chuva = 57
regiaoA_umid = 65

In [ ]:
 # REGIAO B
regiaoB_temp = 22
regiaoB_chuva = 57
regiaoB_umid = 65

In [ ]:
 # REGIAO C
regiaoC_temp = 18
regiaoC_chuva = 96
regiaoC_umid = 70

In [ ]:
# DADOS CLIMÁTICOS REGIAO A
regiaoA_temp = 22
regiaoa_chuva = 67
regiaoA_umid = 65

In [ ]:
# APLICANDO O MODELO
regiaoA_goiaba = regiaoA_temp * w1 + regiaoA_chuva * w2 + regiaoA_umid * w3
print(" Na região A a produção de {} toneladas por hectare".format(regiaoA_goiaba))

 Na região A a produção de 50.5 toneladas por hectare


In [ ]:
RegiaoA = [22,67,65]
RegiaoB = [24,88,95]
RegiaoC = [17,134,50]
RegiaoD = [18,96,70]

In [ ]:
pesos = [w1,w2,w3]

In [ ]:
nomes = [ 'Alice', 'Bob', 'Charlie']
idades = [25,30,35]

# Combinando listas usando zip
lista_combinada = list(zip(nomes, idades))
print(lista_combinada)
# Saída: [ ( 'Alice', 25) ,('Bob', 30) , ('Charlie', 35)]

[('Alice', 25), ('Bob', 30), ('Charlie', 35)]


In [ ]:
def producao_goiaba(regiao, pesos):
    result = 0
    for x, w in zip(regiao, pesos):
           result += x * w
    return result

  # Produção da região A
print(producao_goiaba(RegiaoA, pesos))
  # Produção da região B
print(producao_goiaba(RegiaoB, pesos))

52.5
72.3


In [ ]:
# Importando Numpy
import numpy as np

regiaoA = np.array([22,67,65])

print(type(regiaoA))

pesos = np.array([w1,w2,w3])

print(type(pesos))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
reg_a = np.dot(regiaoA, pesos)
print('A região A: {}'.format(reg_a))

A região A: 52.5


In [ ]:
# NUMPY ( RANGE )
# Lista em Python
arr1 = list(range(2000000))
arr2 = list(range(1000000, 3000000))

# VETOR EM NUMPY
arr1_np =  np.array(arr1)
arr2_np =  np.array(arr2)

In [ ]:
%%time
result = 0
for x1, x2 in zip(arr1,arr2):
  result += x1*x2
print(result)

4666663666667000000
CPU times: user 442 ms, sys: 0 ns, total: 442 ms
Wall time: 444 ms


In [ ]:
%%time
print(np.dot(arr1_np, arr2_np))

4666663666667000000
CPU times: user 3.44 ms, sys: 918 µs, total: 4.36 ms
Wall time: 3.8 ms


In [ ]:
dados_climaticos = np.array([
    [22,67,65],
    [24,88,95],
    [17,134,50],
    [18,96,70],
])

print(dados_climaticos)

[[ 22  67  65]
 [ 24  88  95]
 [ 17 134  50]
 [ 18  96  70]]


In [ ]:
print(pesos.dtype)
print('------')
print(dados_climaticos.dtype)

float64
------
int64


In [ ]:
np.matmul(dados_climaticos, pesos)

array([52.5, 72.3, 56.9, 59.6])

In [ ]:
dados_climaticos @ pesos

array([52.5, 72.3, 56.9, 59.6])

In [ ]:
arr2 = np.array([
    [1,1,1,1],
    [5,6,7,8],
    [9,1,2,3]
])

arr4 = np.array([1,2,3,4])

In [ ]:
#soma
arr2 + arr4

array([[ 2,  3,  4,  5],
       [ 6,  8, 10, 12],
       [10,  3,  5,  7]])